spring.application.name=demo

# 1. Ativa o console do H2 (Você já tem essa)
spring.h2.console.enabled=true

# 2. Define o caminho do banco (essencial para o campo JDBC URL do console)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Libera o acesso ao console (evita erro 403 Forbidden)
spring.h2.console.settings.web-allow-others=true

# 4. Cria as tabelas automaticamente baseado na sua pasta 'model'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect